# Data Preprocessing & Clustering

In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [19]:
df = pd.read_csv("data/Cleaned_Leads.csv")
df.head(10)

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,...,Newspaper,Digital Advertisement,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,City,I agree to pay the amount through cheque,A free copy of Mastering The Interview
0,660737,API,Olark Chat,No,No,0,0.0,0,0.0,Page Visited on Website,...,No,No,No,No,Interested in other courses,No,No,Unknown,No,No
1,660728,API,Organic Search,No,No,0,5.0,674,2.5,Email Opened,...,No,No,No,No,Ringing,No,No,Unknown,No,No
2,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,Email Opened,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,Yes
3,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,Other,...,No,No,No,No,Ringing,No,No,Mumbai,No,No
4,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,Converted to Lead,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,No
5,660680,API,Olark Chat,No,No,0,0.0,0,0.0,Olark Chat Conversation,...,No,No,No,No,Unknown,No,No,Unknown,No,No
6,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,Email Opened,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,No
7,660664,API,Olark Chat,No,No,0,0.0,0,0.0,Olark Chat Conversation,...,No,No,No,No,Unknown,No,No,Unknown,No,No
8,660624,Landing Page Submission,Direct Traffic,No,No,0,2.0,71,2.0,Email Opened,...,No,No,No,No,Unknown,No,No,Thane & Outskirts,No,Yes
9,660616,API,Google,No,No,0,4.0,58,4.0,Email Opened,...,No,No,No,No,Unknown,No,No,Mumbai,No,No

**Dropping Target column for Unsupervised Learning to avoid Data Leakage**

In [20]:
target_column = "Converted"
df.drop(columns=[target_column])

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,Newspaper,Digital Advertisement,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,City,I agree to pay the amount through cheque,A free copy of Mastering The Interview
0,660737,API,Olark Chat,No,No,0.0,0,0.00,Page Visited on Website,Unknown,...,No,No,No,No,Interested in other courses,No,No,Unknown,No,No
1,660728,API,Organic Search,No,No,5.0,674,2.50,Email Opened,India,...,No,No,No,No,Ringing,No,No,Unknown,No,No
2,660727,Landing Page Submission,Direct Traffic,No,No,2.0,1532,2.00,Email Opened,India,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,Yes
3,660719,Landing Page Submission,Direct Traffic,No,No,1.0,305,1.00,Other,India,...,No,No,No,No,Ringing,No,No,Mumbai,No,No
4,660681,Landing Page Submission,Google,No,No,2.0,1428,1.00,Converted to Lead,India,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,579564,Landing Page Submission,Direct Traffic,Yes,No,8.0,1845,2.67,Other,Other,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,No
9236,579546,Landing Page Submission,Direct Traffic,No,No,2.0,238,2.00,SMS Sent,India,...,No,No,No,No,Other,No,No,Mumbai,No,Yes
9237,579545,Landing Page Submission,Direct Traffic,Yes,No,2.0,199,2.00,SMS Sent,India,...,No,No,No,No,Other,No,No,Mumbai,No,Yes
9238,579538,Landing Page Submission,Google,No,No,3.0,499,3.00,SMS Sent,India,...,No,No,No,No,Unknown,No,No,Other Metro Cities,No,No
9239,579533,Landing Page Submission,Direct Traffic,No,No,6.0,1279,3.00,SMS Sent,Other,...,No,No,No,No,Will revert after reading the email,No,No,Other Cities,No,Yes

In [21]:
df.select_dtypes("object").nunique().sort_values(ascending=False)

C:\Users\Tonmoy Saha\AppData\Local\Temp\ipykernel_56860\3982989784.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes("object").nunique().sort_values(ascending=False)

What is your current occupation                  7
City                                             7
Lead Source                                      6
Specialization                                   6
Tags                                             6
Last Activity                                    6
Lead Origin                                      5
What matters most to you in choosing a course    4
Country                                          3
Do Not Call                                      2
Do Not Email                                     2
Newspaper                                        2
X Education Forums                               2
Search                                           2
Newspaper Article                                2
A free copy of Mastering The Interview           2
Digital Advertisement                            2
Through Recommendations                          2
Magazine                                         1
Update me on Supply Chain Content                1
Receive More Updates About Our Courses           1
Get updates on DM Content                        1
I agree to pay the amount through cheque         1
dtype: int64

In [23]:
df.shape

(9240, 28)

In [26]:
df_encoded = pd.get_dummies(df,drop_first=True)
df_encoded.info

<bound method DataFrame.info of       Lead Number  Converted  TotalVisits  Total Time Spent on Website  \
0          660737          0          0.0                            0
1          660728          0          5.0                          674
2          660727          1          2.0                         1532
3          660719          0          1.0                          305
4          660681          1          2.0                         1428
...           ...        ...          ...                          ...
9235       579564          1          8.0                         1845
9236       579546          0          2.0                          238
9237       579545          0          2.0                          199
9238       579538          1          3.0                          499
9239       579533          1          6.0                         1279

      Page Views Per Visit  Lead Origin_Landing Page Submission  \
0                     0.00                                False
1                     2.50                                False
2                     2.00                                 True
3                     1.00                                 True
4                     1.00                                 True
...                    ...                                  ...
9235                  2.67                                 True
9236                  2.00                                 True
9237                  2.00                                 True
9238                  3.00                                 True
9239                  3.00                                 True

      Lead Origin_Lead Add Form  Lead Origin_Lead Import  \
0                         False                    False
1                         False                    False
2                         False                    False
3                         False                    False
4                         False                    False
...                         ...                      ...
9235                      False                    False
9236                      False                    False
9237                      False                    False
9238                      False                    False
9239                      False                    False

      Lead Origin_Quick Add Form  Lead Source_Google  ...  Tags_Ringing  \
0                          False               False  ...         False
1                          False               False  ...          True
2                          False               False  ...         False
3                          False               False  ...          True
4                          False                True  ...         False
...                          ...                 ...  ...           ...
9235                       False               False  ...         False
9236                       False               False  ...         False
9237                       False               False  ...         False
9238                       False                True  ...         False
9239                       False               False  ...         False

      Tags_Unknown  Tags_Will revert after reading the email  \
0            False                                     False
1            False                                     False
2            False                                      True
3            False                                     False
4            False                                      True
...            ...                                       ...
9235         False                                      True
9236         False                                     False
9237         False                                     False
9238          True                                     False
9239         False                                      True

      City_Other Cities  City_Other Cities of Maharashtra  \
0                 False                             False
1                 False                             False
2                 False                             False
3                 False                             False
4                 False                             False
...                 ...                               ...
9235              False                             False
9236              False                             False
9237              False                             False
9238              False                             False
9239               True                             False

      City_Other Metro Cities  City_Thane & Outskirts  City_Tier II Cities  \
0                       False                   False                False
1                       False                   False                False
2                       False                   False                False
3                       False                   False                False
4                       False                   False                False
...                       ...                     ...                  ...
9235                    False                   False                False
9236                    False                   False                False
9237                    False                   False                False
9238                     True                   False                False
9239                    False                   False                False

      City_Unknown  A free copy of Mastering The Interview_Yes
0             True                                       False
1             True                                       False
2            False                                        True
3            False                                       False
4            False                                       False
...            ...                                         ...
9235         False                                       False
9236         False                                        True
9237         False                                        True
9238         False                                       False
9239         False                                        True

[9240 rows x 55 columns]>

In [41]:
stdsclr = StandardScaler()
scaled_data = stdsclr.fit_transform(df_encoded)
df_new = pd.DataFrame(data=scaled_data,columns=df_encoded.columns)
df_new.describe().round(2)

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Google,...,Tags_Ringing,Tags_Unknown,Tags_Will revert after reading the email,City_Other Cities,City_Other Cities of Maharashtra,City_Other Metro Cities,City_Thane & Outskirts,City_Tier II Cities,City_Unknown,A free copy of Mastering The Interview_Yes
count,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,...,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00
mean,0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,...,0.00,0.00,-0.00,-0.00,-0.00,-0.00,-0.00,0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.61,-0.79,-0.71,-0.89,-1.10,-1.06,-0.29,-0.08,-0.01,-0.67,...,-0.39,-0.75,-0.54,-0.28,-0.23,-0.21,-0.30,-0.09,-0.81,-0.67
25%,-0.88,-0.79,-0.51,-0.87,-0.63,-1.06,-0.29,-0.08,-0.01,-0.67,...,-0.39,-0.75,-0.54,-0.28,-0.23,-0.21,-0.30,-0.09,-0.81,-0.67
50%,-0.07,-0.79,-0.09,-0.44,-0.17,0.94,-0.29,-0.08,-0.01,-0.67,...,-0.39,-0.75,-0.54,-0.28,-0.23,-0.21,-0.30,-0.09,-0.81,-0.67
75%,0.86,1.26,0.32,0.82,0.30,0.94,-0.29,-0.08,-0.01,1.49,...,-0.39,1.33,-0.54,-0.28,-0.23,-0.21,-0.30,-0.09,1.23,1.48
max,1.86,1.26,51.37,3.26,24.53,0.94,3.45,12.92,96.12,1.49,...,2.58,1.33,1.86,3.53,4.38,4.83,3.36,11.13,1.23,1.48