# Data Preprocessing & Clustering

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/interim/Cleaned_Leads.csv")
df.head(10)

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,...,X Education Forums,Newspaper,Digital Advertisement,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,I agree to pay the amount through cheque,A free copy of Mastering The Interview
0,660737,API,Olark Chat,No,No,0,0.0,0,0.0,Page Visited on Website,...,No,No,No,No,No,Interested in other courses,No,No,No,No
1,660728,API,Organic Search,No,No,0,5.0,674,2.5,Email Opened,...,No,No,No,No,No,Ringing,No,No,No,No
2,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,Email Opened,...,No,No,No,No,No,Will revert after reading the email,No,No,No,Yes
3,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,Other,...,No,No,No,No,No,Ringing,No,No,No,No
4,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,Converted to Lead,...,No,No,No,No,No,Will revert after reading the email,No,No,No,No
5,660680,API,Olark Chat,No,No,0,0.0,0,0.0,Olark Chat Conversation,...,No,No,No,No,No,Unknown,No,No,No,No
6,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,Email Opened,...,No,No,No,No,No,Will revert after reading the email,No,No,No,No
7,660664,API,Olark Chat,No,No,0,0.0,0,0.0,Olark Chat Conversation,...,No,No,No,No,No,Unknown,No,No,No,No
8,660624,Landing Page Submission,Direct Traffic,No,No,0,2.0,71,2.0,Email Opened,...,No,No,No,No,No,Unknown,No,No,No,Yes
9,660616,API,Google,No,No,0,4.0,58,4.0,Email Opened,...,No,No,No,No,No,Unknown,No,No,No,No

**Dropping Target column for Unsupervised Learning to avoid Data Leakage**

In [3]:
target_column = "Converted"
df.drop(columns=[target_column])

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,X Education Forums,Newspaper,Digital Advertisement,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,I agree to pay the amount through cheque,A free copy of Mastering The Interview
0,660737,API,Olark Chat,No,No,0.0,0,0.00,Page Visited on Website,Unknown,...,No,No,No,No,No,Interested in other courses,No,No,No,No
1,660728,API,Organic Search,No,No,5.0,674,2.50,Email Opened,India,...,No,No,No,No,No,Ringing,No,No,No,No
2,660727,Landing Page Submission,Direct Traffic,No,No,2.0,1532,2.00,Email Opened,India,...,No,No,No,No,No,Will revert after reading the email,No,No,No,Yes
3,660719,Landing Page Submission,Direct Traffic,No,No,1.0,305,1.00,Other,India,...,No,No,No,No,No,Ringing,No,No,No,No
4,660681,Landing Page Submission,Google,No,No,2.0,1428,1.00,Converted to Lead,India,...,No,No,No,No,No,Will revert after reading the email,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,579564,Landing Page Submission,Direct Traffic,Yes,No,8.0,1845,2.67,Other,Other,...,No,No,No,No,No,Will revert after reading the email,No,No,No,No
9236,579546,Landing Page Submission,Direct Traffic,No,No,2.0,238,2.00,SMS Sent,India,...,No,No,No,No,No,Other,No,No,No,Yes
9237,579545,Landing Page Submission,Direct Traffic,Yes,No,2.0,199,2.00,SMS Sent,India,...,No,No,No,No,No,Other,No,No,No,Yes
9238,579538,Landing Page Submission,Google,No,No,3.0,499,3.00,SMS Sent,India,...,No,No,No,No,No,Unknown,No,No,No,No
9239,579533,Landing Page Submission,Direct Traffic,No,No,6.0,1279,3.00,SMS Sent,Other,...,No,No,No,No,No,Will revert after reading the email,No,No,No,Yes

In [5]:
df.shape

(9240, 27)

**Applying one hot encoding for categorical columns**

In [6]:
df_encoded = pd.get_dummies(df,drop_first=True)
df_encoded.info

<bound method DataFrame.info of       Lead Number  Converted  TotalVisits  Total Time Spent on Website  \
0          660737          0          0.0                            0
1          660728          0          5.0                          674
2          660727          1          2.0                         1532
3          660719          0          1.0                          305
4          660681          1          2.0                         1428
...           ...        ...          ...                          ...
9235       579564          1          8.0                         1845
9236       579546          0          2.0                          238
9237       579545          0          2.0                          199
9238       579538          1          3.0                          499
9239       579533          1          6.0                         1279

      Page Views Per Visit  Lead Origin_Landing Page Submission  \
0                     0.00                                False
1                     2.50                                False
2                     2.00                                 True
3                     1.00                                 True
4                     1.00                                 True
...                    ...                                  ...
9235                  2.67                                 True
9236                  2.00                                 True
9237                  2.00                                 True
9238                  3.00                                 True
9239                  3.00                                 True

      Lead Origin_Lead Add Form  Lead Origin_Lead Import  \
0                         False                    False
1                         False                    False
2                         False                    False
3                         False                    False
4                         False                    False
...                         ...                      ...
9235                      False                    False
9236                      False                    False
9237                      False                    False
9238                      False                    False
9239                      False                    False

      Lead Origin_Quick Add Form  Lead Source_Google  ...  \
0                          False               False  ...
1                          False               False  ...
2                          False               False  ...
3                          False               False  ...
4                          False                True  ...
...                          ...                 ...  ...
9235                       False               False  ...
9236                       False               False  ...
9237                       False               False  ...
9238                       False                True  ...
9239                       False               False  ...

      X Education Forums_Yes  Newspaper_Yes  Digital Advertisement_Yes  \
0                      False          False                      False
1                      False          False                      False
2                      False          False                      False
3                      False          False                      False
4                      False          False                      False
...                      ...            ...                        ...
9235                   False          False                      False
9236                   False          False                      False
9237                   False          False                      False
9238                   False          False                      False
9239                   False          False                      False

      Through Recommendations_Yes  Tags_Interested in other courses  \
0                           False                              True
1                           False                             False
2                           False                             False
3                           False                             False
4                           False                             False
...                           ...                               ...
9235                        False                             False
9236                        False                             False
9237                        False                             False
9238                        False                             False
9239                        False                             False

      Tags_Other  Tags_Ringing  Tags_Unknown  \
0          False         False         False
1          False          True         False
2          False         False         False
3          False          True         False
4          False         False         False
...          ...           ...           ...
9235       False         False         False
9236        True         False         False
9237        True         False         False
9238       False         False          True
9239       False         False         False

      Tags_Will revert after reading the email  \
0                                        False
1                                        False
2                                         True
3                                        False
4                                         True
...                                        ...
9235                                      True
9236                                     False
9237                                     False
9238                                     False
9239                                      True

      A free copy of Mastering The Interview_Yes
0                                          False
1                                          False
2                                           True
3                                          False
4                                          False
...                                          ...
9235                                       False
9236                                        True
9237                                        True
9238                                       False
9239                                        True

[9240 rows x 49 columns]>

**Standardizing the values as few fields have much larger scale of values compared to others**

In [7]:
stdsclr = StandardScaler()
scaled_data = stdsclr.fit_transform(df_encoded)
df_processed = pd.DataFrame(data=scaled_data,columns=df_encoded.columns)
df_processed.describe().round(2)

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Google,...,X Education Forums_Yes,Newspaper_Yes,Digital Advertisement_Yes,Through Recommendations_Yes,Tags_Interested in other courses,Tags_Other,Tags_Ringing,Tags_Unknown,Tags_Will revert after reading the email,A free copy of Mastering The Interview_Yes
count,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,...,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00,9240.00
mean,0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,...,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.61,-0.79,-0.71,-0.89,-1.10,-1.06,-0.29,-0.08,-0.01,-0.67,...,-0.01,-0.01,-0.02,-0.03,-0.24,-0.46,-0.39,-0.75,-0.54,-0.67
25%,-0.88,-0.79,-0.51,-0.87,-0.63,-1.06,-0.29,-0.08,-0.01,-0.67,...,-0.01,-0.01,-0.02,-0.03,-0.24,-0.46,-0.39,-0.75,-0.54,-0.67
50%,-0.07,-0.79,-0.09,-0.44,-0.17,0.94,-0.29,-0.08,-0.01,-0.67,...,-0.01,-0.01,-0.02,-0.03,-0.24,-0.46,-0.39,-0.75,-0.54,-0.67
75%,0.86,1.26,0.32,0.82,0.30,0.94,-0.29,-0.08,-0.01,1.49,...,-0.01,-0.01,-0.02,-0.03,-0.24,-0.46,-0.39,1.33,-0.54,1.48
max,1.86,1.26,51.37,3.26,24.53,0.94,3.45,12.92,96.12,1.49,...,96.12,96.12,48.05,36.32,4.12,2.16,2.58,1.33,1.86,1.48

In [8]:
df_processed.to_csv("../data/processed/Processed_Leads.csv",index=False)